name: Build wasm

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'CHelper-Core/**'
      - 'CHelper-Web/**'
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - 'CHelper-Core/**'
      - 'CHelper-Web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install emsdk and build wasm
        run: cd ./CHelper-Web/script && sudo bash ./build-wasm.bash
